name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node 12.x
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Format
        run: npm run check-format

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --ci --coverage --maxWorkers=2

      - name: Build
        run: npm run build
